version: "3"

services:
    # image project
    app:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '80:80'
        working_dir: /var/www/
        volumes:
            - ./:/var/www
