version: "3"

services:
  app:
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
    image: my-app:latest
    restart: unless-stopped
    ports:
      - '80:80'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
