name: 1 - [DEV] deploy

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  dev-tests:
    uses: ./.github/workflows/_tests.yml

  dev-deploy:
    needs: dev-tests
    uses: ./.github/workflows/_terraform.yml
    secrets:
      environment: dev
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
