name: 2 - [PROD] deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  prod-tests:
    uses: ./.github/workflows/_tests.yml

  prod-deploy:
    needs: prod-tests
    uses: ./.github/workflows/_terraform.yml
    secrets:
      environment: prod
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}