name: Destroy terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev or prod)'
        required: true
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183822115:role/github-actions-mavazca-pipeline
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./infra
        run: |
          terraform init \
            -backend-config="bucket=celaummm-us-east-1-terraform-statefile" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=celaummm-us-east-1-terraform-lock"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        id: terraform-destroy
        working-directory: ./infra
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy -var-file="./inventories/${{ inputs.environment }}/terraform.tfvars" -auto-approve