#name: Dev Deploy
#
#on:
#  push:
#    branches:
#      - develop
#
#permissions:
#  id-token: write
#  contents: read
#
#jobs:
#  dev-tests:
#    uses: ./.github/workflows/tests.yml
#
#  dev-terraform:
#    needs: dev-tests
#    uses: ./.github/workflows/terraform-deploy.yml
#    with:
#      environment: dev
#      aws-assume-role-arn: arn:aws:iam::590183822115:role/github-actions-mavazca-pipeline
#      aws-region: us-east-1
#      aws-statefile-s3-bucket: celaummm-us-east-1-terraform-statefile
#      aws-lock-dynamodb-table: celaummm-us-east-1-terraform-lock
#      ecr-repository: dev-us-east-1-laravel-octane-repository
#      ecs-cluster: ecs-cluster-laravel-octane
#      ecs-service: laravel-octane-service